---
{{- if and .Values.persistence.enabled (not .Values.persistence.data.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "aptly-chart.fullname" . }}-data
  annotations:
  {{- range $key, $value := .Values.persistence.data.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "aptly-chart.labels" . | indent 4 }}
spec:
  accessModes: 
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
    {{- if eq "-" .Values.persistence.data.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
