---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aptly-chart.fullname" . }}
  labels:
    {{- include "aptly-chart.labels" . | nindent 4 }}
type: Opaque
data:
  sources_url: {{ .Values.wrapper_env_vars.sources_url | b64enc | quote }}
  merged_mirror_name: {{ .Values.wrapper_env_vars.merged_mirror_name | b64enc | quote }}
  release: {{ .Values.wrapper_env_vars.release | b64enc | quote }}
  password: {{ .Values.wrapper_env_vars.password | b64enc | quote }}
